# Generated by Django 4.1 on 2022-12-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='card_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='expiration_month',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='expiration_year',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
