# Generated by Django 4.1 on 2022-12-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_paymentmethod_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiration_month',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='expiration_year',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
