# Generated by Django 4.1 on 2022-08-28 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gameImages',
            fields=[
                ('imageOne', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('imageTwo', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('imageThree', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('imageFour', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('imageFive', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='gameSpecifications',
            fields=[
                ('osVersion', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu', models.CharField(blank=True, max_length=50, null=True)),
                ('memory', models.CharField(blank=True, max_length=50, null=True)),
                ('gpu', models.CharField(blank=True, max_length=50, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('publisher', models.CharField(blank=True, max_length=50, null=True)),
                ('developer', models.CharField(blank=True, max_length=50, null=True)),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('key', models.URLField(blank=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.gameimages')),
                ('specifications', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.gamespecifications')),
            ],
        ),
    ]
