# Generated by Django 4.1 on 2022-09-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_gameimages_imagefive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameimages',
            name='gameTitle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
