# Generated by Django 4.1 on 2022-09-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gameimages_gametitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamespecifications',
            name='gameTitle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
