# Generated by Django 4.1 on 2022-10-04 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_game_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='game.gameimages'),
        ),
    ]
